pdflatex RB_Manual.tex
bibtex RB_Getting_Started/RB_Getting_Started_content
bibtex RB_Basics_Tutorial/RB_Basics_Tutorial_content
bibtex RB_Data_Tutorial/RB_Data_Tutorial_content
bibtex RB_CTMC_Tutorial/RB_CTMC_Tutorial_content
bibtex RB_Partition_Tutorial/RB_Partition_Tutorial_content
bibtex RB_MCMC_Intro_Tutorial/RB_MCMC_Intro_Tutorial_content
#bibtex RB_MCMC_Tutorial/RB_MCMC_Tutorial_content
bibtex RB_BayesFactor_Tutorial/RB_BayesFactor_Tutorial_content
bibtex RB_DivergenceTime_Tutorial/RB_DivergenceTime_Tutorial_content
bibtex RB_DivergenceTime_Calibration_Tutorial/RB_DivergenceTime_Calibration_Tutorial_content
bibtex RB_DivergenceTime_RelaxedClock_Tutorial/RB_DivergenceTime_RelaxedClock_Tutorial_content
bibtex RB_DiversificationRateIntro_Tutorial/RB_DiversificationRateIntro_Tutorial_content
bibtex RB_DiversificationRate_Tutorial/RB_DiversificationRate_Tutorial_content
bibtex RB_DiversificationRate_Episodic_Tutorial/RB_DiversificationRate_Episodic_Tutorial_content
bibtex RB_DiversificationRate_Environmental_Tutorial/RB_DiversificationRate_Environmental_Tutorial_content
bibtex RB_DiversificationRate_Sampling_Tutorial/RB_DiversificationRate_Sampling_Tutorial_content
bibtex RB_DiversificationRate_BranchSpecific_Tutorial/RB_DiversificationRate_BranchSpecific_Tutorial_content
bibtex RB_GTST_Tutorial/RB_GTST_Tutorial_content
bibtex RB_GeneConcatentation_Tutorial/RB_GeneConcatenation_Tutorial_content
bibtex RB_MultispeciesCoalescent_Tutorial/RB_MultispeciesCoalescent_Tutorial_content
bibtex RB_Biogeography_DEC_Tutorial/RB_Biogeography_DEC_Tutorial_content
bibtex RB_Biogeography_many_area_Tutorial/RB_Biogeography_many_area_Tutorial_content
bibtex RB_PhyloComparative_Tutorial/RB_PhyloComparative_Tutorial_content
pdflatex RB_Manual.tex
pdflatex RB_Manual.tex

rm RB_Manual.aux
rm RB_Manual.blg
rm RB_Manual.log
rm RB_Manual.out
rm RB_Manual.toc

rm RB_Getting_Started/RB_Getting_Started_content.aux
rm RB_Getting_Started/RB_Getting_Started_content.bbl
rm RB_Getting_Started/RB_Getting_Started_content.blg

rm RB_Basics_Tutorial/RB_Basics_Tutorial_content.aux
rm RB_Basics_Tutorial/RB_Basics_Tutorial_content.bbl
rm RB_Basics_Tutorial/RB_Basics_Tutorial_content.blg

rm RB_Data_Tutorial/RB_Data_Tutorial_content.aux
rm RB_Data_Tutorial/RB_Data_Tutorial_content.bbl
rm RB_Data_Tutorial/RB_Data_Tutorial_content.blg

rm RB_MCMC_Intro_Tutorial/RB_MCMC_Intro_Tutorial_content.aux
rm RB_MCMC_Intro_Tutorial/RB_MCMC_Intro_Tutorial_content.bbl
rm RB_MCMC_Intro_Tutorial/RB_MCMC_Intro_Tutorial_content.blg

#rm RB_MCMC_Tutorial/RB_MCMC_Tutorial_content.aux
#rm RB_MCMC_Tutorial/RB_MCMC_Tutorial_content.bbl
#rm RB_MCMC_Tutorial/RB_MCMC_Tutorial_content.blg

rm RB_BayesFactor_Tutorial/RB_BayesFactor_Tutorial_content.aux
rm RB_BayesFactor_Tutorial/RB_BayesFactor_Tutorial_content.bbl
rm RB_BayesFactor_Tutorial/RB_BayesFactor_Tutorial_content.blg

rm RB_CTMC_Tutorial/RB_CTMC_Tutorial_content.aux
rm RB_CTMC_Tutorial/RB_CTMC_Tutorial_content.bbl
rm RB_CTMC_Tutorial/RB_CTMC_Tutorial_content.blg

rm RB_GTST_Tutorial/RB_GTST_Tutorial_content.aux
rm RB_GTST_Tutorial/RB_GTST_Tutorial_content.bbl
rm RB_GTST_Tutorial/RB_GTST_Tutorial_content.blg

rm RB_GeneConcatenation_Tutorial/RB_GeneConcatenation_Tutorial_content.aux
rm RB_GeneConcatenation_Tutorial/RB_GeneConcatenation_Tutorial_content.bbl
rm RB_GeneConcatenation_Tutorial/RB_GeneConcatenation_Tutorial_content.blg

rm RB_MultispeciesCoalescent_Tutorial/RB_MultispeciesCoalescent_Tutorial_content.aux
rm RB_MultispeciesCoalescent_Tutorial/RB_MultispeciesCoalescent_Tutorial_content.bbl
rm RB_MultispeciesCoalescent_Tutorial/RB_MultispeciesCoalescent_Tutorial_content.blg

rm RB_PhyloComparative_Tutorial/RB_PhyloComparative_Tutorial_content.aux
rm RB_PhyloComparative_Tutorial/RB_PhyloComparative_Tutorial_content.bbl
rm RB_PhyloComparative_Tutorial/RB_PhyloComparative_Tutorial_content.blg

rm RB_DivergenceTime_Tutorial/RB_DivergenceTime_Tutorial_content.aux
rm RB_DivergenceTime_Tutorial/RB_DivergenceTime_Tutorial_content.bbl
rm RB_DivergenceTime_Tutorial/RB_DivergenceTime_Tutorial_content.blg

rm RB_DivergenceTime_Calibration_Tutorial/RB_DivergenceTime_Calibration_Tutorial_content.aux
rm RB_DivergenceTime_Calibration_Tutorial/RB_DivergenceTime_Calibration_Tutorial_content.bbl
rm RB_DivergenceTime_Calibration_Tutorial/RB_DivergenceTime_Calibration_Tutorial_content.blg

rm RB_DivergenceTime_RelaxedClock_Tutorial/RB_DivergenceTime_RelaxedClock_Tutorial_content.aux
rm RB_DivergenceTime_RelaxedClock_Tutorial/RB_DivergenceTime_RelaxedClock_Tutorial_content.bbl
rm RB_DivergenceTime_RelaxedClock_Tutorial/RB_DivergenceTime_RelaxedClock_Tutorial_content.blg

rm RB_DiversificationRate_Tutorial/RB_DiversificationRate_Tutorial_content.aux
rm RB_DiversificationRate_Tutorial/RB_DiversificationRate_Tutorial_content.bbl
rm RB_DiversificationRate_Tutorial/RB_DiversificationRate_Tutorial_content.blg

rm RB_DiversificationRate_Episodic_Tutorial/RB_DiversificationRate_Episodic_Tutorial_content.aux
rm RB_DiversificationRate_Episodic_Tutorial/RB_DiversificationRate_Episodic_Tutorial_content.bbl
rm RB_DiversificationRate_Episodic_Tutorial/RB_DiversificationRate_Episodic_Tutorial_content.blg

rm RB_DiversificationRate_Environmental_Tutorial/RB_DiversificationRate_Environmental_Tutorial_content.aux
rm RB_DiversificationRate_Environmental_Tutorial/RB_DiversificationRate_Environmental_Tutorial_content.bbl
rm RB_DiversificationRate_Environmental_Tutorial/RB_DiversificationRate_Environmental_Tutorial_content.blg

rm RB_DiversificationRate_Sampling_Tutorial/RB_DiversificationRate_Sampling_Tutorial_content.aux
rm RB_DiversificationRate_Sampling_Tutorial/RB_DiversificationRate_Sampling_Tutorial_content.bbl
rm RB_DiversificationRate_Sampling_Tutorial/RB_DiversificationRate_Sampling_Tutorial_content.blg

rm RB_DiversificationRate_BranchSpecific_Tutorial/RB_DiversificationRate_BranchSpecific_Tutorial_content.aux
rm RB_DiversificationRate_BranchSpecific_Tutorial/RB_DiversificationRate_BranchSpecific_Tutorial_content.bbl
rm RB_DiversificationRate_BranchSpecific_Tutorial/RB_DiversificationRate_BranchSpecific_Tutorial_content.blg

rm RB_Biogeography_DEC_Tutorial/RB_Biogeography_DEC_Tutorial_content.aux
rm RB_Biogeography_DEC_Tutorial/RB_Biogeography_DEC_Tutorial_content.bbl
rm RB_Biogeography_DEC_Tutorial/RB_Biogeography_DEC_Tutorial_content.blg

rm RB_Biogeography_many_area_Tutorial/RB_Biogeography_many_area_Tutorial_content.aux
rm RB_Biogeography_many_area_Tutorial/RB_Biogeography_many_area_Tutorial_content.bbl
rm RB_Biogeography_many_area_Tutorial/RB_Biogeography_many_area_Tutorial_content.blg
